title: Usages IA4SUP
description: des ressources pour utiliser l'IA dans le cadre de la formation sup√©rieure
theme: just-the-docs

url: https://usagesIA4sup.github.io
repository: usagesIA4sup/usagesIA4sup

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"



aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
